//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimo
    {
        public int id_emprestimo { get; set; }
        public System.DateTime dt_emprestimo { get; set; }
        public System.DateTime dt_devolucao { get; set; }
        public int livro_id_livro { get; set; }
        public int Curso_id_curso { get; set; }
        public int Aluno_id_aluno { get; set; }
        public int Funcionario_id_funcionario { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Livro Livro { get; set; }
    }
}
