//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livro()
        {
            this.Emprestimo = new HashSet<Emprestimo>();
            this.Estoque = new HashSet<Estoque>();
        }
    
        public int id_livro { get; set; }
        public string ds_titulo { get; set; }
        public string ds_tipo { get; set; }
        public string ds_condicoes { get; set; }
        public string nu_isbn { get; set; }
        public string ds_idioma { get; set; }
        public string ds_subtitulo { get; set; }
        public string ds_palavraschaves { get; set; }
        public Nullable<int> nu_volume { get; set; }
        public int Genero_id_genero { get; set; }
        public int Autor_id_autor { get; set; }
        public int Editora_id_editora { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Editora Editora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprestimo> Emprestimo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estoque> Estoque { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
