//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreiInfoA : DbContext
    {
        public FreiInfoA()
            : base("name=FreiInfoA")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Autor> tb_Autor { get; set; }
        public virtual DbSet<tb_Curso> tb_Curso { get; set; }
        public virtual DbSet<tb_Editora> tb_Editora { get; set; }
        public virtual DbSet<tb_Emprestimo> tb_Emprestimo { get; set; }
        public virtual DbSet<tb_Estoque> tb_Estoque { get; set; }
        public virtual DbSet<tb_Funcionario> tb_Funcionario { get; set; }
        public virtual DbSet<tb_Genero> tb_Genero { get; set; }
        public virtual DbSet<tb_Livro> tb_Livro { get; set; }
        public virtual DbSet<tb_Locatario> tb_Locatario { get; set; }
    }
}
