//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Livro()
        {
            this.tb_Emprestimo = new HashSet<tb_Emprestimo>();
            this.tb_Estoque = new HashSet<tb_Estoque>();
        }
    
        public int id_livro { get; set; }
        public string ds_titulo { get; set; }
        public string ds_tipo { get; set; }
        public string ds_condicoes { get; set; }
        public string nu_isbn { get; set; }
        public string ds_idioma { get; set; }
        public string ds_subtitulo { get; set; }
        public string ds_palavraschaves { get; set; }
        public Nullable<int> nu_volume { get; set; }
        public int genero_id_genero { get; set; }
        public int autor_id_autor { get; set; }
        public int editora_id_editora { get; set; }
    
        public virtual tb_Autor tb_Autor { get; set; }
        public virtual tb_Editora tb_Editora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Emprestimo> tb_Emprestimo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Estoque> tb_Estoque { get; set; }
        public virtual tb_Genero tb_Genero { get; set; }
    }
}
