//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_aluno_dados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_aluno_dados()
        {
            this.tb_notificacao = new HashSet<tb_notificacao>();
        }
    
        public int id_aluno_dados { get; set; }
        public string ds_email { get; set; }
        public Nullable<int> tb_aluno_id_aluno { get; set; }
    
        public virtual tb_aluno tb_aluno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_notificacao> tb_notificacao { get; set; }
    }
}
