//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_livro()
        {
            this.tb_emprestimo = new HashSet<tb_emprestimo>();
            this.tb_estoque = new HashSet<tb_estoque>();
        }
    
        public int id_livro { get; set; }
        public string ds_titulo { get; set; }
        public string ds_tipo { get; set; }
        public string ds_condicoes { get; set; }
        public string ds_idioma { get; set; }
        public string nm_editora { get; set; }
        public int nu_volume { get; set; }
        public string nu_isbn { get; set; }
        public string ds_subtitulo { get; set; }
        public string ds_palavrasChaves { get; set; }
        public byte[] img_Capa { get; set; }
        public int autor_id_autor { get; set; }
        public int tb_genero_id_genero { get; set; }
    
        public virtual tb_autor tb_autor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_emprestimo> tb_emprestimo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        public virtual tb_genero tb_genero { get; set; }
    }
}
