//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_notificacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_notificacao()
        {
            this.tb_emprestimo = new HashSet<tb_emprestimo>();
        }
    
        public int id_notificacao { get; set; }
        public bool bt_emailDia { get; set; }
        public bool bt_email5DIa { get; set; }
        public bool bt_emailAtrasado { get; set; }
        public Nullable<int> tb_aluno_dados_id_aluno_dados { get; set; }
        public Nullable<int> tb_locatario_id_locatario { get; set; }
    
        public virtual tb_aluno_dados tb_aluno_dados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_emprestimo> tb_emprestimo { get; set; }
        public virtual tb_locatario tb_locatario { get; set; }
    }
}
