//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Livro_Autor_Genero
    {
        public int id_livro { get; set; }
        public string ds_titulo { get; set; }
        public string ds_palavrasChaves { get; set; }
        public string nm_autor { get; set; }
        public string nm_genero { get; set; }
    }
}
