//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Basico.DB.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_reserva_locatario
    {
        public int id_reserva { get; set; }
        public string nm_locatario { get; set; }
        public Nullable<int> tb_locatario_id_locatario { get; set; }
        public string ds_titulo { get; set; }
        public System.DateTime dt_reserva { get; set; }
    }
}
